### ISSUE TITLE
Why is Keygen down?

### ISSUE THREAD

**Issue by hexicans** [OliFramework/Oli#11]
Hello,
The keygen.matiboux.com is stopped. Why ?

I want use this site.

Thanks

**Comment by matiboux** [comment]
I'm sorry. **This project is not directly associated with Oli**, please ask the project developer himself.

From what I know, the project is **outdated**, and not any update is scheduled yet on it.
*Issue closed.*

**Comment by hexicans** [comment]
Hello,

It's possible to remake that site with you domain name ?

Thanks
